bq-dummy:
  target: sqlfluff
  outputs:
    sqlfluff:
      type: bigquery
      schema: dummy
      method: oauth

duckdb-dummy:
  target: sqlfluff
  outputs:
    sqlfluff:
      type: duckdb
      path: .dbt/dummy.duckdb
