name: sqlfluff

on: [workflow_dispatch] # workflow_dispatch から pull_request に変更する

env: 
  BASE_BRANCH: ${{ github.base_ref }}
  HEAD_BRANCH: ${{ github.head_ref }}

jobs:
  sqlfluff:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Packages
        run: pip install -r "${{ github.workspace }}/requirements.txt"
      - name: Get changed files
        run: |
          git fetch --depth 1 origin ${BASE_BRANCH}
          changed_files=$(git diff origin/${BASE_BRANCH} HEAD --diff-filter=AM --name-only -- "*.sql")
          if [ -n "$changed_files" ]; then
            changed_files="${changed_files//$'\n'/ }"
            echo "files=$changed_files" >> $GITHUB_ENV
          else
            echo "files=SKIP" >> $GITHUB_ENV
          fi
      - name: Fix with SQLFluff
        continue-on-error: true
        run: |
          if [ "$files" != "SKIP" ]; then
            dbt deps
            sqlfluff fix $files -f
          fi
      - name: Check diff
        id: check_diff
        run: |
          git add -N *.sql
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add **/*.sql
          git commit -m "Auto fix with SQLFluff"
          git push origin HEAD:${HEAD_BRANCH}
        if:
          steps.check_diff.outcome == 'failure'
      - name: Lint with SQLFluff
        run: |
          if [ "$files" != "SKIP" ]; then
            dbt deps
            sqlfluff lint --dialect ${{ secrets.DIALECT }} --format github-annotation-native --annotation-level error $files
          else
            echo "No SQL files changed."
          fi
